server:
  port: 8085

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: api-gateway-service

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://localhost:*"
              - "http://127.0.0.1:*"
              - "http://164.92.247.120:*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 7200

      routes:
        # ── API routes ─────────────────────────────────────────────
        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**,/api/v1/user/registration/**,/api/v1/hr/**,/api/v1/mentor/**,/api/v1/oneid/**,/api/v1/password/**,/api/v1/super-admin/**,/api/v1/users/**,/api/v1/device-tokens/**,/api/v1/users/notifications/**,/api/v1/user-notifications/**, /api/v1/users-full-info/**

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/v1/courses/**,/api/v1/lessons/**

        - id: certificate-service
          uri: lb://certificate-service
          predicates:
            - Path=/api/v1/certificates/**

        - id: forum-service
          uri: lb://forum-service
          predicates:
            - Path=/api/v1/forum/forum-comment/**,/api/v1/forums/**,/api/v1/forum/forum-topic/**,/api/v1/forum/likes/**,/api/v1/forum/complaints/**,/api/v1/forum/moderation/**,/api/v1/forum/forbidden-words/**

        - id: webinar-service
          uri: lb://webinar-service
          predicates:
            - Path=/api/v1/webinars/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/orders/**,/api/v1/click/**,/api/v1/paycom/**

        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/api/v1/support/**

        # ── Swagger API-docs proxy (анонимный доступ)
        - id: user-swagger
          uri: lb://user-service
          predicates:
            - Path=/user/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Authorization
            - RemoveRequestHeader=Cookie
            - RewritePath=/user/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        - id: course-swagger
          uri: lb://course-service
          predicates:
            - Path=/course/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Authorization
            - RemoveRequestHeader=Cookie
            - RewritePath=/course/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        - id: certificate-swagger
          uri: lb://certificate-service
          predicates:
            - Path=/certificate/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Authorization
            - RemoveRequestHeader=Cookie
            - RewritePath=/certificate/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        - id: forum-swagger
          uri: lb://forum-service
          predicates:
            - Path=/forum/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Authorization
            - RemoveRequestHeader=Cookie
            - RewritePath=/forum/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        - id: webinar-swagger
          uri: lb://webinar-service
          predicates:
            - Path=/webinar/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Authorization
            - RemoveRequestHeader=Cookie
            - RewritePath=/webinar/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        - id: payment-swagger
          uri: lb://payment-service
          predicates:
            - Path=/payment/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Authorization
            - RemoveRequestHeader=Cookie
            - RewritePath=/payment/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        - id: support-swagger
          uri: lb://support-service
          predicates:
            - Path=/support/v3/api-docs/**
          filters:
            - RemoveRequestHeader=Authorization
            - RemoveRequestHeader=Cookie
            - RewritePath=/support/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        # ── Swagger UI статика с CDN
        - id: swagger-ui-resources
          uri: https://cdn.jsdelivr.net
          predicates:
            - Path=/webjars/**
          filters:
            - RewritePath=/webjars/(?<segment>.*), /npm/swagger-ui-dist@5.9.0/${segment}

        - id: swagger-ui-page
          uri: http://localhost:8085
          predicates:
            - Path=/swagger-ui.html
          filters:
            - SetResponseHeader=Content-Type, text/html

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - url: /user/v3/api-docs
        name: User Service
      - url: /course/v3/api-docs
        name: Course Service
      - url: /certificate/v3/api-docs
        name: Certificate Service
      - url: /forum/v3/api-docs
        name: Forum Service
      - url: /webinar/v3/api-docs
        name: Webinar Service
      - url: /payment/v3/api-docs
        name: Payment Service
      - url: /support/v3/api-docs
        name: Support Service
    urls-primary-name: user-service
    try-it-out-enabled: true

security:
  token: ${SECURITY_TOKEN}
  token-base64: true
  clock-skew-seconds: 60
  max-access-token-ttl-seconds: 3600

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-service:8762/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.web.reactive.HandlerMapping: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
    org.springdoc: DEBUG
