server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/user/registration/**, /api/v1/hr/**, /api/v1/mentor/**, /api/v1/oneid/**,
              /api/v1/password/**, /api/v1/super-admin/**,
              /api/v1/users/**, /api/v1/device-tokens/**,
              /api/v1/users/notifications/**,
              /api/v1/user-notifications/**
        - id: forum-service
          uri: lb://forum-service
          predicates:
            - Path=/api/v1/forum/forum-comment/**, /api/v1/forums/**, /api/v1/forum/forum-topic/**
        - id: webinar-service
          uri: lb://webinar-service
          predicates:
            - Path=/api/v1/webinars/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/orders/**, /api/v1/click/**, /api/v1/paycom/**

        - id: user-swagger
          uri: lb://user-service
          predicates:
            - Path=/user/v3/api-docs/**
          filters:
            - RewritePath=/user/v3/api-docs(?<rem>/?.*), /v3/api-docs${rem}
        - id: forum-swagger
          uri: lb://forum-service
          predicates:
            - Path=/forum/v3/api-docs/**
          filters:
            - RewritePath=/forum/v3/api-docs(?<rem>/?.*), /v3/api-docs${rem}
        - id: webinar-swagger
          uri: lb://webinar-service
          predicates:
            - Path=/webinar/v3/api-docs/**
          filters:
            - RewritePath=/webinar/v3/api-docs(?<rem>/?.*), /v3/api-docs${rem}
        - id: payment-swagger
          uri: lb://payment-service
          predicates:
            - Path=/payment/v3/api-docs/**
          filters:
            - RewritePath=/payment/v3/api-docs(?<rem>/?.*), /v3/api-docs${rem}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    urls:
      - name: user-service
        url: /user/v3/api-docs
      - name: forum-service
        url: /forum/v3/api-docs
      - name: webinar-service
        url: /webinar/v3/api-docs
      - name: payment-service
        url: /payment/v3/api-docs
    urls-primary-name: forum-service
    try-it-out-enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-service:8762/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.web.reactive.HandlerMapping: TRACE
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
