server:
  port: 8085

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://localhost:*"
              - "http://127.0.0.1:*"
              - "http://164.92.247.120:*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 7200
      routes:
        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**,/api/v1/user/registration/**,/api/v1/hr/**,/api/v1/mentor/**,/api/v1/oneid/**,
              /api/v1/password/**,/api/v1/super-admin/**,/api/v1/users/**,/api/v1/device-tokens/**,
              /api/v1/users/notifications/**,/api/v1/user-notifications/**

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/v1/courses/**,/api/v1/lessons/**

        - id: forum-service
          uri: lb://forum-service
          predicates:
            - Path=/api/v1/forum/forum-comment/**,/api/v1/forums/**,/api/v1/forum/forum-topic/**,/api/v1/forum/likes/**,/api/v1/forum/complaints/**,/api/v1/forum/moderation/**,/api/v1/forum/forbidden-words/**

        - id: webinar-service
          uri: lb://webinar-service
          predicates:
            - Path=/api/v1/webinars/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/orders/**,/api/v1/click/**,/api/v1/paycom/**

        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/api/v1/support/**

        # Swagger routes
        - id: user-swagger
          uri: lb://user-service
          predicates:
            - Path=/user/v3/api-docs/**
          filters:
            - RewritePath=/user/v3/api-docs(?<rem>/?.*),/v3/api-docs${rem}

        - id: course-swagger
          uri: lb://course-service
          predicates:
            - Path=/course/v3/api-docs/**
          filters:
            - RewritePath=/course/v3/api-docs(?<rem>/?.*),/v3/api-docs${rem}

        - id: forum-swagger
          uri: lb://forum-service
          predicates:
            - Path=/forum/v3/api-docs/**
          filters:
            - RewritePath=/forum/v3/api-docs(?<rem>/?.*),/v3/api-docs${rem}

        - id: webinar-swagger
          uri: lb://webinar-service
          predicates:
            - Path=/webinar/v3/api-docs/**
          filters:
            - RewritePath=/webinar/v3/api-docs(?<rem>/?.*),/v3/api-docs${rem}

        - id: payment-swagger
          uri: lb://payment-service
          predicates:
            - Path=/payment/v3/api-docs/**
          filters:
            - RewritePath=/payment/v3/api-docs(?<rem>/?.*),/v3/api-docs${rem}

        - id: support-swagger
          uri: lb://support-service
          predicates:
            - Path=/support/v3/api-docs/**
          filters:
            - RewritePath=/support/v3/api-docs(?<rem>/?.*),/v3/api-docs${rem}

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    urls:
      - name: user-service
        url: /user/v3/api-docs
      - name: course-service
        url: /course/v3/api-docs
      - name: forum-service
        url: /forum/v3/api-docs
      - name: webinar-service
        url: /webinar/v3/api-docs
      - name: payment-service
        url: /payment/v3/api-docs
      - name: support-service
        url: /support/v3/api-docs
    urls-primary-name: forum-service
    try-it-out-enabled: true

security:
  token: ${SECURITY_TOKEN}
  token-base64: true
  clock-skew-seconds: 60
  max-access-token-ttl-seconds: 3600

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-service:8762/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
    org.springframework.web.reactive.HandlerMapping: TRACE
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG